version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: banco_mysql
    restart: always
    environment:
      MYSQL_DATABASE: filmes_db
      MYSQL_USER: filmes_user
      MYSQL_PASSWORD: filmes_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: api_filmes
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/filmes_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: filmes_user
      SPRING_DATASOURCE_PASSWORD: filmes_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      TMDB_API_KEY: e70ed1ec2576ea3f6fd6c61c25a56a6b

volumes:
  mysql_data:
